plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md
theme: jekyll-theme-cayman
title: Belajar Sequelize Association
baseurl: "education-intermediate-sequelize-one-to-n"
url: ""
